# Project makefile

all :: subdirs_all main_all

include $(BUILD_ROOT)/.sniffdir/general-$(PLATFORM)-$(BUILDPROFILE).incl
include .sniffdir/$(PLATFORM)-$(BUILDPROFILE).incl
include .sniffdir/$(PLATFORM)-projectbuild.incl
include $(BUILD_ROOT)/general.incl
include .sniffdir/dependencies.incl
